

server:
  port: 9001
  shutdown: graceful
  tomcat: 
    # limit how much time Tomcat should wait b/w accepting a TCP connection 
    # from a client and actually receiving the HTTP request
    connection-timeout: 2s # 
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spase: 5

spring:
  # profiles:
  #   active: prod
  application:
    name: "catalog-service"
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false # retry property below relies on this one
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  # sql: 
  #   init:
  #     mode: always

management:
  endpoints:
    web:
      exposure:
        include: refresh
  
shop:
  greeting: Welcome to the local book catalog (power by config)
  testdata:
    enabled: false


