GET http://localhost:9001/books


###

POST http://localhost:9001/books
Content-Type: application/json

{
    "author": "Lyra Silverstart",
    "title": "Northern Light",
    "isbn": "1231231231",
    "price": 9.99
}