name: bookshop-cloud-native

services:
  catalog-db:
    image: postgres:latest
    container_name: catalog-db
    ports:
      - 5432:5432
    volumes:
      - bookshop-catalog-db:/data/postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: catalog

volumes:
  bookshop-catalog-db:
