apiVersion: apps/v1
# You can also use the kubectl explain <object_
# name> command to check the API version supported by your Kubernetes
# installation for a given object.
kind: Deployment 
metadata: 
  name: catalog-service
  labels:
    app: catalog-service
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: catalog-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          ports:
            - containerPort: 9001
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://catalog-db/catalog"
            - name: SPRING_PROFILE_ACTIVE
              value: testdata
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
