
GET http://localhost:9001/

###

POST http://localhost:9001/actuator/refresh

###

GET http://localhost:9001/books


###

POST http://localhost:9001/books
Content-Type: application/json

{
    "author": "Lyra Silverstart",
    "title": "Northern Light",
    "isbn": "1231231231",
    "price": 9.99
}


###
PUT http://localhost:9001/books/1231231231
Content-Type: application/json

{
    "author": "Lyra Silverstart",
    "title": "Northern Light 2",
    "isbn": "1231231231",
    "price": 9.99
}


### 
DELETE http://localhost:9001/books/1231231231